"""Paper asset helpers.

Single-run assets are diagnostics and are deliberately barred from populating
the manuscript headline. Study-level export will consume a verified study
bundle produced by ``flock analyze-study``.
"""

from __future__ import annotations

from pathlib import Path

PAPER_DIR = Path("paper")
FIGURES = ["convergence_by_cohort.png", "kappa_heatmap.png", "equity_curves.png"]

TABLE_COLUMNS = [
    ("kappa", r"Cohen's $\kappa$"),
    ("agreement", "Agreement"),
    ("portfolio_overlap", "Overlap"),
    ("fingerprint_dispersion", "Fingerprint disp."),
    ("lsv", "LSV"),
]


def export_paper_assets(
    manifest: dict, metrics: dict, contrast: dict | None, report_dir: Path,
    paper_dir: Path = PAPER_DIR,
) -> Path:
    del manifest, metrics, contrast, report_dir, paper_dir
    raise ValueError(
        "single-run paper assets are prohibited; export from a verified study bundle"
    )


def metrics_table_tex(manifest: dict, metrics: dict) -> str:
    header = " & ".join(["Cohort"] + [label for _, label in TABLE_COLUMNS])
    lines = [
        "% auto-generated by `flock analyze --paper`; do not edit by hand",
        f"% run {manifest['run_id']} (config {manifest['config_hash']}, "
        f"git {manifest['git_sha'][:10]})",
        r"\begin{tabular}{l" + "r" * len(TABLE_COLUMNS) + "}",
        r"\toprule",
        header + r" \\",
        r"\midrule",
    ]
    for cohort, vals in metrics.items():
        cells = [_fmt(vals.get(key)) for key, _ in TABLE_COLUMNS]
        lines.append(" & ".join([_escape(cohort)] + cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def headline_macros_tex(contrast: dict | None) -> str:
    lines = ["% auto-generated by `flock analyze --paper`; do not edit by hand"]
    if contrast:
        lo, hi = contrast["ci95"]
        lines += [
            rf"\newcommand{{\deltakappa}}{{{contrast['delta_kappa']:.3f}}}",
            rf"\newcommand{{\deltakappaCIlow}}{{{lo:.3f}}}",
            rf"\newcommand{{\deltakappaCIhigh}}{{{hi:.3f}}}",
            rf"\newcommand{{\deltakappaP}}{{{contrast['p_permutation']:.4f}}}",
        ]
    else:
        lines += [
            r"\newcommand{\deltakappa}{--}",
            r"\newcommand{\deltakappaCIlow}{--}",
            r"\newcommand{\deltakappaCIhigh}{--}",
            r"\newcommand{\deltakappaP}{--}",
        ]
    lines.append("")
    return "\n".join(lines)


def _fmt(v) -> str:
    if v is None:
        return "--"
    try:
        f = float(v)
    except (TypeError, ValueError):
        return _escape(str(v))
    if f != f:  # nan
        return "--"
    return f"{f:.3f}"


def _escape(s: str) -> str:
    return s.replace("_", r"\_")
